
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UniinfoAsp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vFuncionario
{

    public int idFuncionario { get; set; }

    public string nome { get; set; }

    public Nullable<int> ramal { get; set; }

    public Nullable<int> nComputador { get; set; }

    public string email { get; set; }

    public string setor { get; set; }

}

}
