//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniinfo_Desk.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Con_Chamado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Con_Chamado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idChamadoField;
        
        private int idFuncionarioField;
        
        private int idProblemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        private System.DateTime dataChamadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusAtendimentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idChamado {
            get {
                return this.idChamadoField;
            }
            set {
                if ((this.idChamadoField.Equals(value) != true)) {
                    this.idChamadoField = value;
                    this.RaisePropertyChanged("idChamado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idFuncionario {
            get {
                return this.idFuncionarioField;
            }
            set {
                if ((this.idFuncionarioField.Equals(value) != true)) {
                    this.idFuncionarioField = value;
                    this.RaisePropertyChanged("idFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idProblema {
            get {
                return this.idProblemaField;
            }
            set {
                if ((this.idProblemaField.Equals(value) != true)) {
                    this.idProblemaField = value;
                    this.RaisePropertyChanged("idProblema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime dataChamado {
            get {
                return this.dataChamadoField;
            }
            set {
                if ((this.dataChamadoField.Equals(value) != true)) {
                    this.dataChamadoField = value;
                    this.RaisePropertyChanged("dataChamado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string statusAtendimento {
            get {
                return this.statusAtendimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.statusAtendimentoField, value) != true)) {
                    this.statusAtendimentoField = value;
                    this.RaisePropertyChanged("statusAtendimento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfVFuncionario", Namespace="http://tempuri.org/", ItemName="vFuncionario")]
    [System.SerializableAttribute()]
    public class ArrayOfVFuncionario : System.Collections.Generic.List<Uniinfo_Desk.ServiceReference.vFuncionario> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vFuncionario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class vFuncionario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idFuncionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        private System.Nullable<int> ramalField;
        
        private System.Nullable<int> nComputadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string setorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idFuncionario {
            get {
                return this.idFuncionarioField;
            }
            set {
                if ((this.idFuncionarioField.Equals(value) != true)) {
                    this.idFuncionarioField = value;
                    this.RaisePropertyChanged("idFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> ramal {
            get {
                return this.ramalField;
            }
            set {
                if ((this.ramalField.Equals(value) != true)) {
                    this.ramalField = value;
                    this.RaisePropertyChanged("ramal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> nComputador {
            get {
                return this.nComputadorField;
            }
            set {
                if ((this.nComputadorField.Equals(value) != true)) {
                    this.nComputadorField = value;
                    this.RaisePropertyChanged("nComputador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string setor {
            get {
                return this.setorField;
            }
            set {
                if ((object.ReferenceEquals(this.setorField, value) != true)) {
                    this.setorField = value;
                    this.RaisePropertyChanged("setor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento HelloWorldResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Uniinfo_Desk.ServiceReference.HelloWorldResponse HelloWorld(Uniinfo_Desk.ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.HelloWorldResponse> HelloWorldAsync(Uniinfo_Desk.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento ConsultarChamadoResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarChamado", ReplyAction="*")]
        Uniinfo_Desk.ServiceReference.ConsultarChamadoResponse ConsultarChamado(Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarChamado", ReplyAction="*")]
        System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.ConsultarChamadoResponse> ConsultarChamadoAsync(Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento ConsultarFuncionarioResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarFuncionario", ReplyAction="*")]
        Uniinfo_Desk.ServiceReference.ConsultarFuncionarioResponse ConsultarFuncionario(Uniinfo_Desk.ServiceReference.ConsultarFuncionarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarFuncionario", ReplyAction="*")]
        System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.ConsultarFuncionarioResponse> ConsultarFuncionarioAsync(Uniinfo_Desk.ServiceReference.ConsultarFuncionarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncerrarChamado", ReplyAction="*")]
        void EncerrarChamado(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncerrarChamado", ReplyAction="*")]
        System.Threading.Tasks.Task EncerrarChamadoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PosicionarChamado", ReplyAction="*")]
        void PosicionarChamado(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PosicionarChamado", ReplyAction="*")]
        System.Threading.Tasks.Task PosicionarChamadoAsync(int Id);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento loginwpf no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificanivel", ReplyAction="*")]
        Uniinfo_Desk.ServiceReference.verificanivelResponse verificanivel(Uniinfo_Desk.ServiceReference.verificanivelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificanivel", ReplyAction="*")]
        System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.verificanivelResponse> verificanivelAsync(Uniinfo_Desk.ServiceReference.verificanivelRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Uniinfo_Desk.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Uniinfo_Desk.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Uniinfo_Desk.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Uniinfo_Desk.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarChamadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarChamado", Namespace="http://tempuri.org/", Order=0)]
        public Uniinfo_Desk.ServiceReference.ConsultarChamadoRequestBody Body;
        
        public ConsultarChamadoRequest() {
        }
        
        public ConsultarChamadoRequest(Uniinfo_Desk.ServiceReference.ConsultarChamadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsultarChamadoRequestBody {
        
        public ConsultarChamadoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarChamadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarChamadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Uniinfo_Desk.ServiceReference.ConsultarChamadoResponseBody Body;
        
        public ConsultarChamadoResponse() {
        }
        
        public ConsultarChamadoResponse(Uniinfo_Desk.ServiceReference.ConsultarChamadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarChamadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uniinfo_Desk.ServiceReference.Con_Chamado[] ConsultarChamadoResult;
        
        public ConsultarChamadoResponseBody() {
        }
        
        public ConsultarChamadoResponseBody(Uniinfo_Desk.ServiceReference.Con_Chamado[] ConsultarChamadoResult) {
            this.ConsultarChamadoResult = ConsultarChamadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarFuncionarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarFuncionario", Namespace="http://tempuri.org/", Order=0)]
        public Uniinfo_Desk.ServiceReference.ConsultarFuncionarioRequestBody Body;
        
        public ConsultarFuncionarioRequest() {
        }
        
        public ConsultarFuncionarioRequest(Uniinfo_Desk.ServiceReference.ConsultarFuncionarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConsultarFuncionarioRequestBody {
        
        public ConsultarFuncionarioRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarFuncionarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarFuncionarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Uniinfo_Desk.ServiceReference.ConsultarFuncionarioResponseBody Body;
        
        public ConsultarFuncionarioResponse() {
        }
        
        public ConsultarFuncionarioResponse(Uniinfo_Desk.ServiceReference.ConsultarFuncionarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarFuncionarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Uniinfo_Desk.ServiceReference.ArrayOfVFuncionario ConsultarFuncionarioResult;
        
        public ConsultarFuncionarioResponseBody() {
        }
        
        public ConsultarFuncionarioResponseBody(Uniinfo_Desk.ServiceReference.ArrayOfVFuncionario ConsultarFuncionarioResult) {
            this.ConsultarFuncionarioResult = ConsultarFuncionarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verificanivelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verificanivel", Namespace="http://tempuri.org/", Order=0)]
        public Uniinfo_Desk.ServiceReference.verificanivelRequestBody Body;
        
        public verificanivelRequest() {
        }
        
        public verificanivelRequest(Uniinfo_Desk.ServiceReference.verificanivelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verificanivelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginwpf;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senhawpf;
        
        public verificanivelRequestBody() {
        }
        
        public verificanivelRequestBody(string loginwpf, string senhawpf) {
            this.loginwpf = loginwpf;
            this.senhawpf = senhawpf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verificanivelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verificanivelResponse", Namespace="http://tempuri.org/", Order=0)]
        public Uniinfo_Desk.ServiceReference.verificanivelResponseBody Body;
        
        public verificanivelResponse() {
        }
        
        public verificanivelResponse(Uniinfo_Desk.ServiceReference.verificanivelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verificanivelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verificanivelResult;
        
        public verificanivelResponseBody() {
        }
        
        public verificanivelResponseBody(string verificanivelResult) {
            this.verificanivelResult = verificanivelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Uniinfo_Desk.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Uniinfo_Desk.ServiceReference.WebServiceSoap>, Uniinfo_Desk.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uniinfo_Desk.ServiceReference.HelloWorldResponse Uniinfo_Desk.ServiceReference.WebServiceSoap.HelloWorld(Uniinfo_Desk.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Uniinfo_Desk.ServiceReference.HelloWorldRequest inValue = new Uniinfo_Desk.ServiceReference.HelloWorldRequest();
            inValue.Body = new Uniinfo_Desk.ServiceReference.HelloWorldRequestBody();
            Uniinfo_Desk.ServiceReference.HelloWorldResponse retVal = ((Uniinfo_Desk.ServiceReference.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.HelloWorldResponse> Uniinfo_Desk.ServiceReference.WebServiceSoap.HelloWorldAsync(Uniinfo_Desk.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            Uniinfo_Desk.ServiceReference.HelloWorldRequest inValue = new Uniinfo_Desk.ServiceReference.HelloWorldRequest();
            inValue.Body = new Uniinfo_Desk.ServiceReference.HelloWorldRequestBody();
            return ((Uniinfo_Desk.ServiceReference.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uniinfo_Desk.ServiceReference.ConsultarChamadoResponse Uniinfo_Desk.ServiceReference.WebServiceSoap.ConsultarChamado(Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest request) {
            return base.Channel.ConsultarChamado(request);
        }
        
        public Uniinfo_Desk.ServiceReference.Con_Chamado[] ConsultarChamado() {
            Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest inValue = new Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest();
            inValue.Body = new Uniinfo_Desk.ServiceReference.ConsultarChamadoRequestBody();
            Uniinfo_Desk.ServiceReference.ConsultarChamadoResponse retVal = ((Uniinfo_Desk.ServiceReference.WebServiceSoap)(this)).ConsultarChamado(inValue);
            return retVal.Body.ConsultarChamadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.ConsultarChamadoResponse> Uniinfo_Desk.ServiceReference.WebServiceSoap.ConsultarChamadoAsync(Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest request) {
            return base.Channel.ConsultarChamadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.ConsultarChamadoResponse> ConsultarChamadoAsync() {
            Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest inValue = new Uniinfo_Desk.ServiceReference.ConsultarChamadoRequest();
            inValue.Body = new Uniinfo_Desk.ServiceReference.ConsultarChamadoRequestBody();
            return ((Uniinfo_Desk.ServiceReference.WebServiceSoap)(this)).ConsultarChamadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uniinfo_Desk.ServiceReference.ConsultarFuncionarioResponse Uniinfo_Desk.ServiceReference.WebServiceSoap.ConsultarFuncionario(Uniinfo_Desk.ServiceReference.ConsultarFuncionarioRequest request) {
            return base.Channel.ConsultarFuncionario(request);
        }
        
        public Uniinfo_Desk.ServiceReference.ArrayOfVFuncionario ConsultarFuncionario() {
            Uniinfo_Desk.ServiceReference.ConsultarFuncionarioRequest inValue = new Uniinfo_Desk.ServiceReference.ConsultarFuncionarioRequest();
            inValue.Body = new Uniinfo_Desk.ServiceReference.ConsultarFuncionarioRequestBody();
            Uniinfo_Desk.ServiceReference.ConsultarFuncionarioResponse retVal = ((Uniinfo_Desk.ServiceReference.WebServiceSoap)(this)).ConsultarFuncionario(inValue);
            return retVal.Body.ConsultarFuncionarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.ConsultarFuncionarioResponse> Uniinfo_Desk.ServiceReference.WebServiceSoap.ConsultarFuncionarioAsync(Uniinfo_Desk.ServiceReference.ConsultarFuncionarioRequest request) {
            return base.Channel.ConsultarFuncionarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.ConsultarFuncionarioResponse> ConsultarFuncionarioAsync() {
            Uniinfo_Desk.ServiceReference.ConsultarFuncionarioRequest inValue = new Uniinfo_Desk.ServiceReference.ConsultarFuncionarioRequest();
            inValue.Body = new Uniinfo_Desk.ServiceReference.ConsultarFuncionarioRequestBody();
            return ((Uniinfo_Desk.ServiceReference.WebServiceSoap)(this)).ConsultarFuncionarioAsync(inValue);
        }
        
        public void EncerrarChamado(int Id) {
            base.Channel.EncerrarChamado(Id);
        }
        
        public System.Threading.Tasks.Task EncerrarChamadoAsync(int Id) {
            return base.Channel.EncerrarChamadoAsync(Id);
        }
        
        public void PosicionarChamado(int Id) {
            base.Channel.PosicionarChamado(Id);
        }
        
        public System.Threading.Tasks.Task PosicionarChamadoAsync(int Id) {
            return base.Channel.PosicionarChamadoAsync(Id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Uniinfo_Desk.ServiceReference.verificanivelResponse Uniinfo_Desk.ServiceReference.WebServiceSoap.verificanivel(Uniinfo_Desk.ServiceReference.verificanivelRequest request) {
            return base.Channel.verificanivel(request);
        }
        
        public string verificanivel(string loginwpf, string senhawpf) {
            Uniinfo_Desk.ServiceReference.verificanivelRequest inValue = new Uniinfo_Desk.ServiceReference.verificanivelRequest();
            inValue.Body = new Uniinfo_Desk.ServiceReference.verificanivelRequestBody();
            inValue.Body.loginwpf = loginwpf;
            inValue.Body.senhawpf = senhawpf;
            Uniinfo_Desk.ServiceReference.verificanivelResponse retVal = ((Uniinfo_Desk.ServiceReference.WebServiceSoap)(this)).verificanivel(inValue);
            return retVal.Body.verificanivelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.verificanivelResponse> Uniinfo_Desk.ServiceReference.WebServiceSoap.verificanivelAsync(Uniinfo_Desk.ServiceReference.verificanivelRequest request) {
            return base.Channel.verificanivelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Uniinfo_Desk.ServiceReference.verificanivelResponse> verificanivelAsync(string loginwpf, string senhawpf) {
            Uniinfo_Desk.ServiceReference.verificanivelRequest inValue = new Uniinfo_Desk.ServiceReference.verificanivelRequest();
            inValue.Body = new Uniinfo_Desk.ServiceReference.verificanivelRequestBody();
            inValue.Body.loginwpf = loginwpf;
            inValue.Body.senhawpf = senhawpf;
            return ((Uniinfo_Desk.ServiceReference.WebServiceSoap)(this)).verificanivelAsync(inValue);
        }
    }
}
